# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  component_name: shipping 
  javaMaven: true
  
resources:
  repositories:
    - repository: templates
      type: git
      name: azd-ci-templates
      
steps:

#- template: codecheck.yml@templates

- script: |
    mvn package
    mkdir publish 
    cp target/shipping-1.0-jar-with-dependencies.jar publish/shipping.jar
  displayName: Package maven code
- task: Docker@2
  inputs:
    containerRegistry: 'Docker-Hub'
    repository: 'rkalluru/d51-shipping'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '1.0.$(Build.BuildId)'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'ce99914a-0f7d-4c46-9ccc-e4d025115ea9/aceb203d-03c1-40f9-b6e1-2c1450fcebd6'
    vstsFeedPackagePublish: 'shipping'
    versionOption: 'custom'
    versionPublish: '1.0.$(Build.BuildId)'
  
  
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)/publish'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'ce99914a-0f7d-4c46-9ccc-e4d025115ea9/f0174cff-2623-4600-a29f-0eb8a06b0a0c'
    vstsFeedPackagePublish: 'shipping'
    versionOption: 'patch'
    packagePublishDescription: 'RoboShop Shipping'